//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	networkingv1alpha3 "github.com/dubml/client-go/pkg/apis/networking/v1alpha3"
	applyconfigurationnetworkingv1alpha3 "github.com/dubml/client-go/pkg/applyconfiguration/networking/v1alpha3"
	scheme "github.com/dubml/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TransitServicesGetter has a method to return a TransitServiceInterface.
// A group's client should implement this interface.
type TransitServicesGetter interface {
	TransitServices(namespace string) TransitServiceInterface
}

// TransitServiceInterface has methods to work with TransitService resources.
type TransitServiceInterface interface {
	Create(ctx context.Context, transitService *networkingv1alpha3.TransitService, opts v1.CreateOptions) (*networkingv1alpha3.TransitService, error)
	Update(ctx context.Context, transitService *networkingv1alpha3.TransitService, opts v1.UpdateOptions) (*networkingv1alpha3.TransitService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, transitService *networkingv1alpha3.TransitService, opts v1.UpdateOptions) (*networkingv1alpha3.TransitService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkingv1alpha3.TransitService, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkingv1alpha3.TransitServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1alpha3.TransitService, err error)
	Apply(ctx context.Context, transitService *applyconfigurationnetworkingv1alpha3.TransitServiceApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha3.TransitService, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, transitService *applyconfigurationnetworkingv1alpha3.TransitServiceApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha3.TransitService, err error)
	TransitServiceExpansion
}

// transitServices implements TransitServiceInterface
type transitServices struct {
	*gentype.ClientWithListAndApply[*networkingv1alpha3.TransitService, *networkingv1alpha3.TransitServiceList, *applyconfigurationnetworkingv1alpha3.TransitServiceApplyConfiguration]
}

// newTransitServices returns a TransitServices
func newTransitServices(c *NetworkingV1alpha3Client, namespace string) *transitServices {
	return &transitServices{
		gentype.NewClientWithListAndApply[*networkingv1alpha3.TransitService, *networkingv1alpha3.TransitServiceList, *applyconfigurationnetworkingv1alpha3.TransitServiceApplyConfiguration](
			"transitservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1alpha3.TransitService { return &networkingv1alpha3.TransitService{} },
			func() *networkingv1alpha3.TransitServiceList { return &networkingv1alpha3.TransitServiceList{} },
		),
	}
}
